use std::{error::Error, fs::File, io::Write};

use chrono::Local;

use crate::domain::{club::Club, Category, Tag};

fn autogen_commenter(file: &mut File) -> Result<(), Box<dyn Error>> {
    writeln!(file, "-- AUTOGENERATED MOCK DATA, DO NOT MODIFY")?;
    writeln!(
        file,
        "-- GENERATED AT {}",
        Local::now().format("%Y-%m-%d %H:%M:%S")
    )?;

    Ok(())
}

pub fn dump_all(
    categories: &Vec<Category>,
    tags: &Vec<&'static Tag>,
    clubs: Vec<Club>,
    club_parent: uuid::Uuid,
    file: &mut File,
) -> Result<(), Box<dyn Error>> {
    autogen_commenter(file)?;

    writeln!(file, "BEGIN;")?;

    crate::dumper::category::dump(categories, file)?;

    crate::dumper::tag::dump(tags, file)?;

    crate::dumper::club::dump(clubs, file, club_parent)?;

    writeln!(file, "COMMIT;")?;

    Ok(())
}
