linters:
  enable:
    - cyclop
    - exportloopref
    - gocritic
    - gosec
    - ineffassign
    - misspell
    - prealloc
    - unconvert
    - unparam
    - goimports
    - whitespace

linters-settings:
  whitespace:
    multi-func: true

issues:
  exclude-rules:
    - path: tests/api/helpers/
      linters:
        - cyclop
    - path: src/config/production.go
      linters:
        - cyclop
