application:
  port: 8080
  host: 127.0.0.1
  baseurl: http://127.0.0.1
database:
  host: 127.0.0.1
  port: 5432
  username: postgres
  password: password
  databasename: sac
  requiressl: false
superuser:
  password: password
auth:
  accesstoken: g(r|##*?>\Qp}h37e+,T2
  accesstokenexpiry: 60 # in minutes
  refreshtoken: amk*2!gG}1i"8D9RwJS$p
  refreshtokenexpiry: 30 # in days
