export const API_BASE_URL = 'http://localhost:8080/api/v1';

export const college = [
    { label: 'College of Arts, Media and Design', value: 'CAMD' },
    { label: "D'Amore-McKim School of Business", value: 'DMSB' },
    { label: 'Khoury College of Computer Sciences', value: 'KCCS' },
    { label: 'College of Engineering', value: 'CE' },
    { label: 'Bouvé College of Health Sciences', value: 'BCHS' },
    { label: 'School of Law', value: 'SL' },
    { label: 'College of Professional Studies', value: 'CPS' },
    { label: 'College of Science', value: 'CS' },
    { label: 'College of Social Sciences and Humanities', value: 'CSSH' }
];

export const majorArr = [
    'Africana Studies',
    'American Sign Language',
    'American Sign Language – English Interpreting',
    'Applied Physics',
    'Architectural Studies',
    'Architecture',
    'Art: Art, Visual Studies',
    'Behavioral Neuroscience*',
    'Biochemistry',
    'Bioengineering',
    'Biology',
    'Biomedical Physics',
    'Bouvé Undeclared',
    'Business Administration: Accounting',
    'Business Administration: Accounting and Advisory Services',
    'Business Administration: Brand Management',
    'Business Administration: Business Analytics',
    'Business Administration: Corporate Innovation',
    'Business Administration: Entrepreneurial Startups',
    'Business Administration: Family Business',
    'Business Administration: Finance',
    'Business Administration: Fintech',
    'Business Administration: Healthcare Management and Consulting',
    'Business Administration: Management',
    'Business Administration: Management Information Systems',
    'Business Administration: Marketing',
    'Business Administration: Marketing Analytics',
    'Business Administration: Social Innovation and Entrepreneurship',
    'Business Administration: Supply Chain Management',
    'Business Administration: Undeclared',
    'Business Administration*',
    'CAMD Undeclared',
    'Cell and Molecular Biology',
    'Chemical Engineering',
    'Chemistry',
    'Civil Engineering',
    'COE Undeclared',
    'Communication Studies',
    'Computer Engineering',
    'Computer Science*',
    'Computing and Law',
    'Criminology and Criminal Justice',
    'Cultural Anthropology',
    'Cybersecurity',
    'Data Science',
    'Design',
    'Discover Oakland*',
    'Economics',
    'Electrical Engineering',
    'English',
    'Environmental and Sustainability Sciences',
    'Environmental Engineering',
    'Environmental Science',
    'Environmental Studies',
    'Explore all 180+ combined majors!',
    'Explore Program for undeclared students',
    'Game Art and Animation',
    'Game Design',
    'Global Asian Studies',
    'Health Science*',
    'History',
    'History, Culture, and Law',
    'Human Services',
    'Industrial Engineering',
    'International Affairs',
    'International Business: Accounting',
    'International Business: Accounting and Advisory Services',
    'International Business: Brand Management',
    'International Business: Business Analytics',
    'International Business: Corporate Innovation',
    'International Business: Entrepreneurial Startups',
    'International Business: Family Business',
    'International Business: Finance',
    'International Business: Fintech',
    'International Business: Healthcare Management and Consulting',
    'International Business: Management',
    'International Business: Management Information Systems',
    'International Business: Marketing',
    'International Business: Marketing Analytics',
    'International Business: Social Innovation and Entrepreneurship',
    'International Business: Supply Chain Management',
    'International Business: Undeclared',
    'Journalism',
    'Landscape Architecture',
    'Linguistics',
    'Marine Biology',
    'Mathematics',
    'Mechanical Engineering',
    'Media and Screen Studies',
    'Media Arts',
    'Music',
    'Music Industry',
    'Music Technology',
    'Northeastern Explore Program (Undeclared)',
    'Nursing',
    'Pharmaceutical Sciences',
    'Pharmacy (PharmD)',
    'Philosophy',
    'Physics',
    'Political Science',
    'Politics, Philosophy, Economics*',
    'Psychology*',
    'Public Health*',
    'Public Relations',
    'Religious Studies',
    'Sociology',
    'Spanish',
    'Speech Language Pathology and Audiology',
    'Theatre'
];
