basePath: /api/v1
definitions:
  models.Category:
    properties:
      category_name:
        maxLength: 255
        type: string
      created_at:
        example: "2023-09-20T16:34:50Z"
        type: string
      id:
        example: 1
        type: integer
      updated_at:
        example: "2023-09-20T16:34:50Z"
        type: string
    required:
    - category_name
    type: object
  models.College:
    enum:
    - CAMD
    - DMSB
    - KCCS
    - CE
    - BCHS
    - SL
    - CPS
    - CS
    - CSSH
    type: string
    x-enum-comments:
      BCHS: Bouvé College of Health Sciences
      CAMD: College of Arts, Media and Design
      CE: College of Engineering
      CPS: College of Professional Studies
      CS: College of Science
      CSSH: College of Social Sciences and Humanities
      DMSB: D'Amore-McKim School of Business
      KCCS: Khoury College of Computer Sciences
      SL: School of Law
    x-enum-varnames:
    - CAMD
    - DMSB
    - KCCS
    - CE
    - BCHS
    - SL
    - CPS
    - CS
    - CSSH
  models.Tag:
    properties:
      category_id:
        minimum: 1
        type: integer
      created_at:
        example: "2023-09-20T16:34:50Z"
        type: string
      id:
        example: 1
        type: integer
      name:
        maxLength: 255
        type: string
      updated_at:
        example: "2023-09-20T16:34:50Z"
        type: string
    required:
    - category_id
    - name
    type: object
  models.User:
    properties:
      college:
        allOf:
        - $ref: '#/definitions/models.College'
        maxLength: 255
      created_at:
        example: "2023-09-20T16:34:50Z"
        type: string
      email:
        maxLength: 255
        type: string
      first_name:
        maxLength: 255
        type: string
      id:
        example: 1
        type: integer
      last_name:
        maxLength: 255
        type: string
      nuid:
        type: string
      updated_at:
        example: "2023-09-20T16:34:50Z"
        type: string
      user_role:
        allOf:
        - $ref: '#/definitions/models.UserRole'
        maxLength: 255
      year:
        allOf:
        - $ref: '#/definitions/models.Year'
        maximum: 6
        minimum: 1
    required:
    - college
    - email
    - first_name
    - last_name
    - nuid
    - user_role
    - year
    type: object
  models.UserRole:
    enum:
    - super
    - clubAdmin
    - student
    type: string
    x-enum-varnames:
    - Super
    - ClubAdmin
    - Student
  models.Year:
    enum:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    type: integer
    x-enum-varnames:
    - First
    - Second
    - Third
    - Fourth
    - Fifth
    - Graduate
host: 127.0.0.1:8080
info:
  contact:
    email: oduneye.d@northeastern.edu and ladley.g@northeastern.edu
    name: David Oduneye and Garrett Ladley
  description: Backend Server for SAC App
  title: SAC API
  version: "1.0"
paths:
  /api/v1/category/:
    post:
      description: Creates a category that is used to group tags
      operationId: create-category
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Category'
        "400":
          description: category with that name already exists
          schema:
            type: string
        "500":
          description: failed to create category
          schema:
            type: string
      summary: Create a category
      tags:
      - category
  /api/v1/tags/:
    post:
      consumes:
      - application/json
      description: Creates a tag
      operationId: create-tag
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Tag'
        "400":
          description: failed to validate the data
          schema:
            type: string
        "500":
          description: failed to create tag
          schema:
            type: string
      summary: Creates a tag
      tags:
      - tag
  /api/v1/tags/{id}:
    delete:
      description: Deletes a tag
      operationId: delete-tag
      parameters:
      - description: Tag ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "204":
          description: No Content
        "400":
          description: failed to validate id
          schema:
            type: string
        "404":
          description: failed to find tag
          schema:
            type: string
        "500":
          description: failed to delete tag
          schema:
            type: string
      summary: Deletes a tag
      tags:
      - tag
    get:
      description: Returns a tag
      operationId: get-tag
      parameters:
      - description: Tag ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Tag'
        "400":
          description: failed to validate id
          schema:
            type: string
        "404":
          description: faied to find tag
          schema:
            type: string
        "500":
          description: failed to retrieve tag
          schema:
            type: string
      summary: Gets a tag
      tags:
      - tag
    patch:
      consumes:
      - application/json
      description: Updates a tag
      operationId: update-tag
      parameters:
      - description: Tag ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Tag'
        "400":
          description: failed to validate the data
          schema:
            type: string
        "404":
          description: failed to find tag
          schema:
            type: string
        "500":
          description: failed to update tag
          schema:
            type: string
      summary: Updates a tag
      tags:
      - tag
  /api/v1/users/:
    get:
      description: Returns all users
      operationId: get-all-users
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.User'
            type: array
        "500":
          description: failed to get all users
          schema:
            type: string
      summary: Gets all users
      tags:
      - user
swagger: "2.0"
