name: Auto Request Review

on:
  pull_request:
    types: [opened, ready_for_review, reopened]

jobs:
  auto-request-review:
    runs-on: ubuntu-latest
    steps:
      - name: Request review from the TLs and 1 random team member
        uses: necojackarc/auto-request-review@v0.12.0
        with:
          token: ${{ secrets.PAT_FOR_AUTO_REQUEST_REVIEW }}
          config: .github/reviewers.yml
