name: "Auto Assign Author"

on:
  pull_request:
    types: [opened, ready_for_review, reopened]

jobs:
  add-reviews:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v1.2.6
        with:
          configuration-path: ".github/assignees.yml"
