name: Mobile

permissions: read-all

on:
  push:
    paths:
      - frontend/sac-mobile/**
      - .github/workflows/mobile.yml
  pull_request:
    types: opened
    paths:
      - frontend/sac-mobile/**
      - .github/workflows/mobile.yml

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: yarn
          cache-dependency-path: frontend/sac-mobile/yarn.lock

      - name: Install dependencies
        run: |
          cd frontend/sac-mobile
          yarn install

      - name: Lint
        run: |
          cd frontend/sac-mobile
          yarn lint

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: yarn
          cache-dependency-path: frontend/sac-mobile/yarn.lock

      - name: Install dependencies
        run: |
          cd frontend/sac-mobile
          yarn install

      - name: Test
        run: |
          cd frontend/sac-mobile
          yarn test
