name: Mobile

permissions: read-all

on:
  push:
    paths:
      - backend/**
      - .github/workflows/backend.yml
  pull_request:
    types: opened
    paths:
      - backend/**
      - .github/workflows/backend.yml

jobs:
    lint:
        name: Lint
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [18.x]
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                node-version: ${{ matrix.node-version }}
                cache: yarn
                cache-dependency-path: frontend/sac-mobile/yarn.lock

            - name: Install dependencies
              run: |
                cd frontend/sac-mobile
                yarn install

            - name: Lint
              run: |
                cd frontend/sac-mobile
                yarn lint

    test:
        name: Test
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [18.x]
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                node-version: ${{ matrix.node-version }}
                cache: yarn
                cache-dependency-path: frontend/sac-mobile/yarn.lock

            - name: Install dependencies
              run: |
                cd frontend/sac-mobile
                yarn install

            - name: Test
              run: |
                cd frontend/sac-mobile
                yarn test